classdef MAD < Algorithms.CDAlg
    properties
        nMADUsed = uint8(255);
    end
    methods
        function obj = MAD(k)
            obj@Algorithms.CDAlg('Multivariate Alteration Detection', ...
                ['A. A. Nielsen, K. Conradsen, and J. J. Simpson,', ...
                '¡°Multivariate Alteration Detection (MAD) and MAF', ...
                'Postprocessing in Multispectral, Bitemporal Image Data:', ...
                'New Approaches to Change Detection Studies,¡±', ...
                'Remote Sensing of Environment, vol. 64, no. 1, pp. 1¨C19, 1998.'] ...
                ); 
            if exist('k', 'var'), obj.nMADUsed=uint8(k); end
        end
        [DI, k] = detectChange(obj, t1, t2);
    end
end